-- Execute este arquivo no SQL Editor do Supabase.
-- Ele cria/ajusta as tabelas usadas pelo app e libera as politicas
-- necessarias para a chave anonima do frontend durante este projeto.

create table if not exists public.funcionario (
  id bigint generated by default as identity primary key,
  nome text,
  email text unique,
  cargo text,
  role text,
  posicao_preferencial text,
  created_at timestamptz default now()
);

create table if not exists public.sala (
  id bigint generated by default as identity primary key,
  nome text not null,
  localizacao text,
  tipo text,
  categoria text,
  descricao text,
  capacidade integer,
  status text,
  disponivel boolean default true,
  motivo_manutencao text,
  planta_url text,
  created_at timestamptz default now()
);

create table if not exists public.mesa (
  id bigint generated by default as identity primary key,
  sala_id bigint references public.sala(id) on delete cascade,
  codigo_mesa text not null,
  created_at timestamptz default now()
);

create table if not exists public.posicao (
  id bigint generated by default as identity primary key,
  sala_id bigint references public.sala(id) on delete cascade,
  codigo_cadeira text not null,
  coordenadas_x numeric,
  coordenadas_y numeric,
  status text,
  disponivel boolean default true,
  motivo_manutencao text,
  created_at timestamptz default now()
);

create table if not exists public.imagem_sala (
  id bigint generated by default as identity primary key,
  sala_id bigint references public.sala(id) on delete cascade,
  nome_ambiente text,
  imagem_url text,
  created_at timestamptz default now()
);

create table if not exists public.equipamento (
  id bigint generated by default as identity primary key,
  sala_id bigint references public.sala(id) on delete cascade,
  posicao_id bigint references public.posicao(id) on delete cascade,
  nome text not null,
  descricao text,
  tipo text,
  status text default 'DISPONIVEL',
  created_at timestamptz default now()
);

create table if not exists public.reserva (
  id bigint generated by default as identity primary key,
  funcionario_id bigint references public.funcionario(id) on delete cascade,
  posicao_id bigint references public.posicao(id) on delete set null,
  data_inicio timestamptz default now(),
  data_fim timestamptz,
  status text default 'ATIVA',
  created_at timestamptz default now()
);

alter table public.funcionario add column if not exists role text;
alter table public.funcionario add column if not exists posicao_preferencial text;
alter table public.sala add column if not exists tipo text;
alter table public.sala add column if not exists categoria text;
alter table public.sala add column if not exists descricao text;
alter table public.sala add column if not exists capacidade integer;
alter table public.sala add column if not exists status text;
alter table public.sala add column if not exists disponivel boolean default true;
alter table public.sala add column if not exists motivo_manutencao text;
alter table public.sala add column if not exists planta_url text;
alter table public.posicao add column if not exists status text;
alter table public.posicao add column if not exists disponivel boolean default true;
alter table public.posicao add column if not exists motivo_manutencao text;
alter table public.imagem_sala add column if not exists sala_id bigint references public.sala(id) on delete cascade;
alter table public.imagem_sala add column if not exists nome_ambiente text;
alter table public.imagem_sala add column if not exists imagem_url text;
alter table public.imagem_sala add column if not exists created_at timestamptz default now();
alter table public.equipamento add column if not exists sala_id bigint references public.sala(id) on delete cascade;
alter table public.equipamento add column if not exists posicao_id bigint references public.posicao(id) on delete cascade;
alter table public.equipamento add column if not exists descricao text;
alter table public.equipamento add column if not exists tipo text;
alter table public.equipamento add column if not exists status text default 'DISPONIVEL';
alter table public.reserva add column if not exists status text default 'ATIVA';
alter table public.reserva alter column status set default 'ATIVA';
alter table public.reserva add column if not exists data_inicio timestamptz default now();
alter table public.reserva add column if not exists data_fim timestamptz;

update public.reserva
set status = 'CANCELADA'
where lower(coalesce(status, '')) = 'cancelada';

update public.reserva
set status = 'ATIVA'
where status is null
   or lower(status) in ('ativa', 'pendente', 'confirmada');

update public.sala
set status = case
    when status is null or status = '' then case when coalesce(disponivel, true) then 'DISPONIVEL' else 'INDISPONIVEL' end
    when upper(status) in ('DISPONIVEL', 'INDISPONIVEL', 'MANUTENCAO') then upper(status)
    else case when coalesce(disponivel, true) then 'DISPONIVEL' else 'INDISPONIVEL' end
  end;

update public.sala
set disponivel = status = 'DISPONIVEL';

update public.posicao
set status = case
    when status is null or status = '' then case when coalesce(disponivel, true) then 'DISPONIVEL' else 'INDISPONIVEL' end
    when upper(status) in ('DISPONIVEL', 'INDISPONIVEL', 'MANUTENCAO') then upper(status)
    else case when coalesce(disponivel, true) then 'DISPONIVEL' else 'INDISPONIVEL' end
  end;

update public.posicao
set disponivel = status = 'DISPONIVEL';

create unique index if not exists funcionario_email_unique_idx
  on public.funcionario (lower(email))
  where email is not null;

create index if not exists mesa_sala_id_idx on public.mesa (sala_id);
create index if not exists posicao_sala_id_idx on public.posicao (sala_id);
create index if not exists equipamento_posicao_id_idx on public.equipamento (posicao_id);
create index if not exists equipamento_sala_id_idx on public.equipamento (sala_id);
create index if not exists reserva_funcionario_id_idx on public.reserva (funcionario_id);
create index if not exists reserva_posicao_id_idx on public.reserva (posicao_id);
create index if not exists imagem_sala_sala_id_idx on public.imagem_sala (sala_id);

drop index if exists reserva_posicao_ativa_unique_idx;
create index if not exists reserva_posicao_periodo_idx
  on public.reserva (posicao_id, data_inicio, data_fim)
  where posicao_id is not null
    and coalesce(upper(status), 'ATIVA') <> 'CANCELADA';

alter table public.funcionario enable row level security;
alter table public.sala enable row level security;
alter table public.mesa enable row level security;
alter table public.posicao enable row level security;
alter table public.equipamento enable row level security;
alter table public.reserva enable row level security;
alter table public.imagem_sala enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.funcionario to anon, authenticated;
grant select, insert, update, delete on public.sala to anon, authenticated;
grant select, insert, update, delete on public.mesa to anon, authenticated;
grant select, insert, update, delete on public.posicao to anon, authenticated;
grant select, insert, update, delete on public.equipamento to anon, authenticated;
grant select, insert, update, delete on public.reserva to anon, authenticated;
grant select, insert, update, delete on public.imagem_sala to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

drop policy if exists funcionario_select_public on public.funcionario;
drop policy if exists funcionario_insert_public on public.funcionario;
drop policy if exists funcionario_update_public on public.funcionario;
drop policy if exists funcionario_delete_public on public.funcionario;
create policy funcionario_select_public on public.funcionario for select using (true);
create policy funcionario_insert_public on public.funcionario for insert with check (true);
create policy funcionario_update_public on public.funcionario for update using (true) with check (true);
create policy funcionario_delete_public on public.funcionario for delete using (true);

drop policy if exists sala_select_public on public.sala;
drop policy if exists sala_insert_public on public.sala;
drop policy if exists sala_update_public on public.sala;
drop policy if exists sala_delete_public on public.sala;
create policy sala_select_public on public.sala for select using (true);
create policy sala_insert_public on public.sala for insert with check (true);
create policy sala_update_public on public.sala for update using (true) with check (true);
create policy sala_delete_public on public.sala for delete using (true);

drop policy if exists mesa_select_public on public.mesa;
drop policy if exists mesa_insert_public on public.mesa;
drop policy if exists mesa_update_public on public.mesa;
drop policy if exists mesa_delete_public on public.mesa;
create policy mesa_select_public on public.mesa for select using (true);
create policy mesa_insert_public on public.mesa for insert with check (true);
create policy mesa_update_public on public.mesa for update using (true) with check (true);
create policy mesa_delete_public on public.mesa for delete using (true);

drop policy if exists posicao_select_public on public.posicao;
drop policy if exists posicao_insert_public on public.posicao;
drop policy if exists posicao_update_public on public.posicao;
drop policy if exists posicao_delete_public on public.posicao;
create policy posicao_select_public on public.posicao for select using (true);
create policy posicao_insert_public on public.posicao for insert with check (true);
create policy posicao_update_public on public.posicao for update using (true) with check (true);
create policy posicao_delete_public on public.posicao for delete using (true);

drop policy if exists equipamento_select_public on public.equipamento;
drop policy if exists equipamento_insert_public on public.equipamento;
drop policy if exists equipamento_update_public on public.equipamento;
drop policy if exists equipamento_delete_public on public.equipamento;
create policy equipamento_select_public on public.equipamento for select using (true);
create policy equipamento_insert_public on public.equipamento for insert with check (true);
create policy equipamento_update_public on public.equipamento for update using (true) with check (true);
create policy equipamento_delete_public on public.equipamento for delete using (true);

drop policy if exists reserva_select_public on public.reserva;
drop policy if exists reserva_insert_public on public.reserva;
drop policy if exists reserva_update_public on public.reserva;
drop policy if exists reserva_delete_public on public.reserva;
create policy reserva_select_public on public.reserva for select using (true);
create policy reserva_insert_public on public.reserva for insert with check (true);
create policy reserva_update_public on public.reserva for update using (true) with check (true);
create policy reserva_delete_public on public.reserva for delete using (true);

drop policy if exists imagem_sala_select_public on public.imagem_sala;
drop policy if exists imagem_sala_insert_public on public.imagem_sala;
drop policy if exists imagem_sala_update_public on public.imagem_sala;
drop policy if exists imagem_sala_delete_public on public.imagem_sala;
create policy imagem_sala_select_public on public.imagem_sala for select using (true);
create policy imagem_sala_insert_public on public.imagem_sala for insert with check (true);
create policy imagem_sala_update_public on public.imagem_sala for update using (true) with check (true);
create policy imagem_sala_delete_public on public.imagem_sala for delete using (true);

insert into storage.buckets (id, name, public)
values ('imagens', 'imagens', true)
on conflict (id) do update set public = true;

drop policy if exists imagens_storage_select_public on storage.objects;
drop policy if exists imagens_storage_insert_public on storage.objects;
drop policy if exists imagens_storage_update_public on storage.objects;
drop policy if exists imagens_storage_delete_public on storage.objects;
create policy imagens_storage_select_public on storage.objects
  for select using (bucket_id = 'imagens');
create policy imagens_storage_insert_public on storage.objects
  for insert with check (bucket_id = 'imagens');
create policy imagens_storage_update_public on storage.objects
  for update using (bucket_id = 'imagens') with check (bucket_id = 'imagens');
create policy imagens_storage_delete_public on storage.objects
  for delete using (bucket_id = 'imagens');

insert into public.mesa (sala_id, codigo_mesa)
select s.id, 'M01'
from public.sala s
where not exists (
  select 1 from public.mesa m where m.sala_id = s.id
);

insert into public.posicao (sala_id, codigo_cadeira, coordenadas_x, coordenadas_y, disponivel)
select
  s.id,
  'P' || lpad(n::text, 2, '0'),
  n,
  1,
  true
from public.sala s
cross join generate_series(1, 4) as n
where not exists (
  select 1 from public.posicao p where p.sala_id = s.id
);
