"use client";

import { ChangeEvent, FormEvent, useEffect, useMemo, useState, useSyncExternalStore } from "react";
import { useRouter } from "next/navigation";
import { formatDate, formatSupabaseError, normalizarTexto, valueOrFallback } from "@/lib/app-utils";
import {
  clearFuncionarioSession,
  getFuncionarioServerSnapshot,
  getFuncionarioSnapshot,
  isAdministrador,
  parseFuncionario,
  subscribeFuncionarioSnapshot,
} from "@/lib/session";
import { supabase } from "@/lib/supabase";
import styles from "./admin.module.css";

const STATUS_DISPONIVEL = "DISPONIVEL";
const STATUS_MANUTENCAO = "MANUTENCAO";
const STATUS_RESERVA_CANCELADA = "CANCELADA";
const PLANTA_BUCKET = "imagens";

const SQL_MANUTENCAO = `alter table public.sala add column if not exists motivo_manutencao text;
alter table public.posicao add column if not exists motivo_manutencao text;`;

const SQL_IMAGEM_SALA = `create table if not exists public.imagem_sala (
  id bigint generated by default as identity primary key,
  sala_id bigint references public.sala(id) on delete cascade,
  nome_ambiente text,
  imagem_url text,
  created_at timestamptz default now()
);

alter table public.imagem_sala add column if not exists sala_id bigint references public.sala(id) on delete cascade;
alter table public.imagem_sala add column if not exists nome_ambiente text;
alter table public.imagem_sala add column if not exists imagem_url text;
alter table public.imagem_sala add column if not exists created_at timestamptz default now();`;

type Sala = {
  id: number | string;
  nome?: string | null;
  localizacao?: string | null;
  status?: string | null;
  disponivel?: boolean | null;
  planta_url?: string | null;
  motivo_manutencao?: string | null;
  created_at?: string | null;
};

type Posicao = {
  id: number | string;
  sala_id?: number | string | null;
  codigo_cadeira?: string | null;
  coordenadas_x?: number | string | null;
  coordenadas_y?: number | string | null;
  status?: string | null;
  disponivel?: boolean | null;
  motivo_manutencao?: string | null;
  created_at?: string | null;
};

type Reserva = {
  id: number | string;
  funcionario_id?: number | string | null;
  posicao_id?: number | string | null;
  data_inicio?: string | null;
  data_fim?: string | null;
  datainicio?: string | null;
  datafim?: string | null;
  status?: string | null;
  created_at?: string | null;
};

type Funcionario = {
  id: number | string;
  nome?: string | null;
  email?: string | null;
};

function isEmManutencao(item: Pick<Sala | Posicao, "status" | "disponivel">) {
  const status = normalizarTexto(item.status);
  return item.disponivel === false || status === "manutencao" || status === "indisponivel";
}

function isReservaCancelada(status?: string | null) {
  return normalizarTexto(status) === "cancelada";
}

function safeFilePart(value: string, fallback: string) {
  return (
    value
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || fallback
  );
}

function safeUploadedName(value: string, fallback: string) {
  return (
    value
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .replace(/[^a-z0-9.]+/g, "-")
      .replace(/^-|-$/g, "") || fallback
  );
}

export default function AdminPage() {
  const router = useRouter();
  const funcionarioSnapshot = useSyncExternalStore(
    subscribeFuncionarioSnapshot,
    getFuncionarioSnapshot,
    getFuncionarioServerSnapshot
  );
  const funcionario = useMemo(() => parseFuncionario(funcionarioSnapshot), [funcionarioSnapshot]);
  const isAdmin = isAdministrador(funcionario);

  const [salas, setSalas] = useState<Sala[]>([]);
  const [posicoes, setPosicoes] = useState<Posicao[]>([]);
  const [reservas, setReservas] = useState<Reserva[]>([]);
  const [funcionarios, setFuncionarios] = useState<Funcionario[]>([]);
  const [nomeAmbientePlanta, setNomeAmbientePlanta] = useState("");
  const [plantaFile, setPlantaFile] = useState<File | null>(null);
  const [plantaPreview, setPlantaPreview] = useState("");
  const [motivosPosicao, setMotivosPosicao] = useState<Record<string, string>>({});
  const [motivosSala, setMotivosSala] = useState<Record<string, string>>({});
  const [message, setMessage] = useState("");
  const [messageType, setMessageType] = useState<"error" | "success">("success");
  const [isLoading, setIsLoading] = useState(true);
  const [isUploading, setIsUploading] = useState(false);
  const [savingId, setSavingId] = useState<string | null>(null);

  useEffect(() => {
    carregarDados();
  }, []);

  async function carregarDados() {
    setIsLoading(true);
    setMessage("");

    const [salasResult, posicoesResult, reservasResult, funcionariosResult] = await Promise.all([
      supabase.from("sala").select("*").order("nome", { ascending: true }),
      supabase.from("posicao").select("*").order("id", { ascending: true }),
      supabase.from("reserva").select("*").order("created_at", { ascending: false }),
      supabase.from("funcionario").select("id, nome, email").order("nome", { ascending: true }),
    ]);

    setIsLoading(false);

    const firstError = salasResult.error || posicoesResult.error || reservasResult.error;
    if (firstError) {
      console.error(firstError);
      setMessageType("error");
      setMessage(formatSupabaseError("NÃ£o foi possÃ­vel carregar o painel", firstError));
      return;
    }

    if (funcionariosResult.error) {
      console.warn("FuncionÃ¡rios nÃ£o carregados.", funcionariosResult.error);
    }

    const salasData = (salasResult.data || []) as Sala[];
    const posicoesData = (posicoesResult.data || []) as Posicao[];

    setSalas(salasData);
    setPosicoes(posicoesData);
    setReservas((reservasResult.data || []) as Reserva[]);
    setFuncionarios((funcionariosResult.data || []) as Funcionario[]);
    setMotivosSala(
      salasData.reduce<Record<string, string>>((acc, sala) => {
        acc[String(sala.id)] = sala.motivo_manutencao || "";
        return acc;
      }, {})
    );
    setMotivosPosicao(
      posicoesData.reduce<Record<string, string>>((acc, posicao) => {
        acc[String(posicao.id)] = posicao.motivo_manutencao || "";
        return acc;
      }, {})
    );
  }

  function handlePlantaFile(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0] || null;
    setPlantaFile(file);
    setPlantaPreview(file ? URL.createObjectURL(file) : "");
  }

  async function uploadPlantaImagem(nomeAmbiente: string) {
    if (!plantaFile) {
      return null;
    }

    const safeRoomName = safeFilePart(nomeAmbiente, "ambiente");
    const safeName = safeUploadedName(plantaFile.name, "planta");
    const path = `ambientes/${safeRoomName}/${Date.now()}-${safeName}`;
    const upload = await supabase.storage.from(PLANTA_BUCKET).upload(path, plantaFile, {
      cacheControl: "3600",
      upsert: true,
    });

    if (upload.error) {
      console.error(upload.error);
      throw new Error(
        `Não foi possível enviar a imagem. Verifique se o bucket '${PLANTA_BUCKET}' existe e permite upload.`
      );
    }

    const { data } = supabase.storage.from(PLANTA_BUCKET).getPublicUrl(path);
    return data.publicUrl;
  }

  function isMissingPlantaUrlColumn(error: { code?: string | null; message?: string | null }) {
    return error.code === "42703" || normalizarTexto(error.message).includes("planta_url");
  }

  async function buscarOuCriarSala(nomeAmbiente: string, plantaUrl: string | null) {
    const existente = await supabase.from("sala").select("id").ilike("nome", nomeAmbiente).maybeSingle();

    if (existente.error) {
      throw new Error(formatSupabaseError("NÃ£o foi possÃ­vel localizar o ambiente", existente.error));
    }

    if (existente.data) {
      const update = await supabase
        .from("sala")
        .update({ planta_url: plantaUrl, disponivel: true, status: STATUS_DISPONIVEL })
        .eq("id", existente.data.id)
        .select("id")
        .single();

      if (update.error && isMissingPlantaUrlColumn(update.error)) {
        const fallbackUpdate = await supabase
          .from("sala")
          .update({ disponivel: true, status: STATUS_DISPONIVEL })
          .eq("id", existente.data.id)
          .select("id")
          .single();

        if (fallbackUpdate.error) {
          throw new Error(formatSupabaseError("Não foi possível atualizar o ambiente", fallbackUpdate.error));
        }

        return fallbackUpdate.data as { id: number | string };
      }

      if (update.error) {
        throw new Error(formatSupabaseError("NÃ£o foi possÃ­vel atualizar a planta do ambiente", update.error));
      }

      return update.data as { id: number | string };
    }

    const insert = await supabase
      .from("sala")
      .insert({ nome: nomeAmbiente, planta_url: plantaUrl, disponivel: true, status: STATUS_DISPONIVEL })
      .select("id")
      .single();

    if (insert.error && isMissingPlantaUrlColumn(insert.error)) {
      const fallbackInsert = await supabase
        .from("sala")
        .insert({ nome: nomeAmbiente, disponivel: true, status: STATUS_DISPONIVEL })
        .select("id")
        .single();

      if (fallbackInsert.error) {
        throw new Error(formatSupabaseError("Não foi possível criar o ambiente", fallbackInsert.error));
      }

      return fallbackInsert.data as { id: number | string };
    }

    if (insert.error) {
      throw new Error(formatSupabaseError("NÃ£o foi possÃ­vel criar o ambiente para a planta", insert.error));
    }

    return insert.data as { id: number | string };
  }

  async function salvarImagemSala(salaId: number | string | null, nomeAmbiente: string, imagemUrl: string) {
    const payload = {
      sala_id: salaId ?? null,
      nome_ambiente: nomeAmbiente,
      imagem_url: imagemUrl,
    };

    const { error } = await supabase.from("imagem_sala").insert(payload);

    if (error) {
      throw new Error(
        `${formatSupabaseError("A imagem foi salva no ambiente, mas a tabela imagem_sala precisa de ajuste", error)}\n\nSQL necessÃ¡rio:\n${SQL_IMAGEM_SALA}`
      );
    }
  }

  async function handleUploadPlanta(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    const nomeAmbiente = nomeAmbientePlanta.trim();
    if (!nomeAmbiente || !plantaFile) {
      setMessageType("error");
      setMessage("Informe o nome do ambiente e anexe uma imagem.");
      return;
    }

    setIsUploading(true);
    setMessage("");

    try {
      const imagemUrl = await uploadPlantaImagem(nomeAmbiente);
      if (!imagemUrl) {
        throw new Error("Selecione uma imagem para enviar.");
      }

      let salaId: number | string | null = null;
      let avisoVinculo = "";

      try {
        const sala = await buscarOuCriarSala(nomeAmbiente, imagemUrl);
        salaId = sala.id;
      } catch (salaError) {
        console.warn("Imagem enviada, mas não foi possível vincular/criar a sala.", salaError);
        avisoVinculo = " A imagem foi registrada sem vínculo com sala.";
      }

      await salvarImagemSala(salaId, nomeAmbiente, imagemUrl);

      setNomeAmbientePlanta("");
      setPlantaFile(null);
      setPlantaPreview("");
      setMessageType("success");
      setMessage(`Imagem da planta enviada com sucesso.${avisoVinculo}`);
      carregarDados();
    } catch (error) {
      console.error(error);
      setMessageType("error");
      setMessage(error instanceof Error ? error.message : "NÃ£o foi possÃ­vel enviar a planta.");
      carregarDados();
    } finally {
      setIsUploading(false);
    }
  }

  async function atualizarManutencao(tipo: "sala" | "posicao", id: number | string, emManutencao: boolean) {
    const stateKey = `${tipo}-${id}`;
    const motivo = tipo === "sala" ? motivosSala[String(id)] || "" : motivosPosicao[String(id)] || "";

    if (emManutencao && !motivo.trim()) {
      setMessageType("error");
      setMessage("Informe o motivo da manutenÃ§Ã£o antes de marcar como indisponÃ­vel.");
      return;
    }

    setSavingId(stateKey);
    setMessage("");

    const payload = {
      disponivel: !emManutencao,
      status: emManutencao ? STATUS_MANUTENCAO : STATUS_DISPONIVEL,
      motivo_manutencao: emManutencao ? motivo.trim() : null,
    };

    const { error } = await supabase.from(tipo).update(payload).eq("id", id);
    setSavingId(null);

    if (error) {
      console.error(error);
      setMessageType("error");
      setMessage(`${formatSupabaseError("NÃ£o foi possÃ­vel atualizar a manutenÃ§Ã£o", error)}\n\nSQL necessÃ¡rio:\n${SQL_MANUTENCAO}`);
      return;
    }

    setMessageType("success");
    setMessage(emManutencao ? "Recurso marcado em manutenÃ§Ã£o." : "Recurso liberado para reserva.");
    carregarDados();
  }

  async function cancelarReserva(reserva: Reserva) {
    if (!window.confirm(`Cancelar a reserva ${reserva.id}?`)) {
      return;
    }

    setSavingId(`reserva-${reserva.id}`);
    setMessage("");

    const { error } = await supabase.from("reserva").update({ status: STATUS_RESERVA_CANCELADA }).eq("id", reserva.id);
    setSavingId(null);

    if (error) {
      console.error(error);
      setMessageType("error");
      setMessage(formatSupabaseError("NÃ£o foi possÃ­vel cancelar a reserva", error));
      return;
    }

    setMessageType("success");
    setMessage("Reserva cancelada com sucesso.");
    carregarDados();
  }

  function handleLogout() {
    clearFuncionarioSession();
    router.push("/");
  }

  const salaPorId = new Map(salas.map((item) => [String(item.id), item]));
  const funcionarioPorId = new Map(funcionarios.map((item) => [String(item.id), item]));
  const posicaoPorId = new Map(posicoes.map((item) => [String(item.id), item]));
  const reservasAtivas = reservas.filter((reserva) => !isReservaCancelada(reserva.status)).length;

  if (!funcionario) {
    return (
      <main className={styles.blocked}>
        <h1>Acesso administrativo</h1>
        <p>FaÃ§a login como administrador para acessar esta Ã¡rea.</p>
        <button type="button" onClick={() => router.push("/")}>
          Ir para login
        </button>
      </main>
    );
  }

  if (!isAdmin) {
    return (
      <main className={styles.blocked}>
        <h1>Acesso restrito</h1>
        <p>Seu usuÃ¡rio nÃ£o tem permissÃ£o de administrador.</p>
        <button type="button" onClick={() => router.push("/home")}>
          Voltar para Home
        </button>
      </main>
    );
  }

  return (
    <div className={styles.page}>
      <header className={styles.header}>
        <button className={styles.logoArea} type="button" onClick={() => router.push("/home")}>
          <span className={styles.logoAccent}>&gt;</span>
          <span className={styles.logoText}>accenture</span>
        </button>

        <div className={styles.headerActions}>
          <div>
            <span>Administrador</span>
            <strong>{funcionario.nome || funcionario.email}</strong>
          </div>
          <button type="button" onClick={() => router.push("/home")}>
            Home
          </button>
          <button type="button" onClick={handleLogout}>
            Sair
          </button>
        </div>
      </header>

      <main className={styles.main}>
        <section className={styles.hero}>
          <p className={styles.eyebrow}>Admin</p>
          <h1>Painel rÃ¡pido de apresentaÃ§Ã£o</h1>
          <p>Upload da planta, reservas e manutenÃ§Ã£o de ambientes e posiÃ§Ãµes.</p>
        </section>

        {message && <p className={`${styles.message} ${styles[messageType]}`}>{message}</p>}

        <section className={styles.metrics}>
          <article>
            <span>Ambientes</span>
            <strong>{salas.length}</strong>
          </article>
          <article>
            <span>PosiÃ§Ãµes</span>
            <strong>{posicoes.length}</strong>
          </article>
          <article>
            <span>Reservas ativas</span>
            <strong>{reservasAtivas}</strong>
          </article>
        </section>

        <section className={styles.panel}>
          <div className={styles.panelHeader}>
            <div>
              <p className={styles.eyebrow}>Planta</p>
              <h2>Enviar imagem do ambiente</h2>
            </div>
          </div>
          <form className={styles.form} onSubmit={handleUploadPlanta}>
            <label>
              Nome do ambiente
              <input
                value={nomeAmbientePlanta}
                onChange={(event) => setNomeAmbientePlanta(event.target.value)}
                placeholder="Sala A"
              />
            </label>
            <label>
              Imagem
              <input type="file" accept="image/*" onChange={handlePlantaFile} />
            </label>
            {plantaPreview && <div className={styles.preview} style={{ backgroundImage: `url(${plantaPreview})` }} />}
            <button type="submit" disabled={isUploading}>
              {isUploading ? "Enviando..." : "Enviar imagem"}
            </button>
          </form>
        </section>

        <section className={styles.panel}>
          <div className={styles.panelHeader}>
            <div>
              <p className={styles.eyebrow}>Reservas</p>
              <h2>Visualizar e cancelar</h2>
            </div>
            <button type="button" onClick={carregarDados}>
              {isLoading ? "Carregando..." : "Atualizar"}
            </button>
          </div>
          <div className={styles.dataTable}>
            <div className={styles.reservasHead}>
              <span>ID</span>
              <span>ResponsÃ¡vel</span>
              <span>PosiÃ§Ã£o</span>
              <span>Ambiente</span>
              <span>InÃ­cio</span>
              <span>Fim</span>
              <span>Status</span>
              <span>AÃ§Ã£o</span>
            </div>
            {reservas.map((reserva) => {
              const posicao = posicaoPorId.get(String(reserva.posicao_id));
              const sala = posicao ? salaPorId.get(String(posicao.sala_id)) : undefined;
              const funcionarioReserva = reserva.funcionario_id
                ? funcionarioPorId.get(String(reserva.funcionario_id))
                : undefined;
              const cancelada = isReservaCancelada(reserva.status);
              const isSaving = savingId === `reserva-${reserva.id}`;

              return (
                <div key={reserva.id} className={styles.reservasRow}>
                  <span>{reserva.id}</span>
                  <span>{funcionarioReserva?.nome || funcionarioReserva?.email || valueOrFallback(reserva.funcionario_id)}</span>
                  <span>{posicao?.codigo_cadeira || valueOrFallback(reserva.posicao_id)}</span>
                  <span>{valueOrFallback(sala?.nome)}</span>
                  <span>{formatDate(reserva.data_inicio || reserva.datainicio)}</span>
                  <span>{formatDate(reserva.data_fim || reserva.datafim)}</span>
                  <span>{cancelada ? "Cancelada" : valueOrFallback(reserva.status, "Ativa")}</span>
                  <button type="button" disabled={cancelada || isSaving} onClick={() => cancelarReserva(reserva)}>
                    {isSaving ? "Cancelando..." : "Cancelar"}
                  </button>
                </div>
              );
            })}
            {reservas.length === 0 && <div className={styles.emptyRow}>Nenhuma reserva encontrada.</div>}
          </div>
        </section>

        <section className={styles.panel}>
          <div className={styles.panelHeader}>
            <div>
              <p className={styles.eyebrow}>PosiÃ§Ãµes</p>
              <h2>ManutenÃ§Ã£o de posiÃ§Ãµes</h2>
            </div>
          </div>
          <div className={styles.dataTable}>
            <div className={styles.posicoesHead}>
              <span>ID</span>
              <span>CÃ³digo</span>
              <span>Ambiente</span>
              <span>Status</span>
              <span>Motivo</span>
              <span>AÃ§Ã£o</span>
            </div>
            {posicoes.map((posicao) => {
              const emManutencao = isEmManutencao(posicao);
              const isSaving = savingId === `posicao-${posicao.id}`;

              return (
                <div key={posicao.id} className={styles.posicoesRow}>
                  <span>{posicao.id}</span>
                  <span>{posicao.codigo_cadeira || `PosiÃ§Ã£o ${posicao.id}`}</span>
                  <span>{valueOrFallback(salaPorId.get(String(posicao.sala_id))?.nome)}</span>
                  <span>{emManutencao ? "ManutenÃ§Ã£o" : "DisponÃ­vel"}</span>
                  <input
                    value={motivosPosicao[String(posicao.id)] || ""}
                    onChange={(event) =>
                      setMotivosPosicao((current) => ({ ...current, [String(posicao.id)]: event.target.value }))
                    }
                    placeholder="Monitor quebrado"
                  />
                  <button
                    type="button"
                    disabled={isSaving}
                    onClick={() => atualizarManutencao("posicao", posicao.id, !emManutencao)}
                  >
                    {isSaving ? "Salvando..." : emManutencao ? "Liberar" : "ManutenÃ§Ã£o"}
                  </button>
                </div>
              );
            })}
            {posicoes.length === 0 && <div className={styles.emptyRow}>Nenhuma posiÃ§Ã£o cadastrada.</div>}
          </div>
        </section>

        <section className={styles.panel}>
          <div className={styles.panelHeader}>
            <div>
              <p className={styles.eyebrow}>Ambientes</p>
              <h2>ManutenÃ§Ã£o de salas</h2>
            </div>
          </div>
          <div className={styles.dataTable}>
            <div className={styles.salasHead}>
              <span>ID</span>
              <span>Nome</span>
              <span>LocalizaÃ§Ã£o</span>
              <span>Planta</span>
              <span>Status</span>
              <span>Motivo</span>
              <span>AÃ§Ã£o</span>
            </div>
            {salas.map((sala) => {
              const emManutencao = isEmManutencao(sala);
              const isSaving = savingId === `sala-${sala.id}`;

              return (
                <div key={sala.id} className={styles.salasRow}>
                  <span>{sala.id}</span>
                  <span>{valueOrFallback(sala.nome)}</span>
                  <span>{valueOrFallback(sala.localizacao)}</span>
                  <span>
                    {sala.planta_url ? (
                      <a href={sala.planta_url} target="_blank" rel="noreferrer">
                        Abrir
                      </a>
                    ) : (
                      "Sem planta"
                    )}
                  </span>
                  <span>{emManutencao ? "ManutenÃ§Ã£o" : "DisponÃ­vel"}</span>
                  <input
                    value={motivosSala[String(sala.id)] || ""}
                    onChange={(event) =>
                      setMotivosSala((current) => ({ ...current, [String(sala.id)]: event.target.value }))
                    }
                    placeholder="Sala em manutenÃ§Ã£o"
                  />
                  <button
                    type="button"
                    disabled={isSaving}
                    onClick={() => atualizarManutencao("sala", sala.id, !emManutencao)}
                  >
                    {isSaving ? "Salvando..." : emManutencao ? "Liberar" : "ManutenÃ§Ã£o"}
                  </button>
                </div>
              );
            })}
            {salas.length === 0 && <div className={styles.emptyRow}>Nenhum ambiente cadastrado.</div>}
          </div>
        </section>
      </main>
    </div>
  );
}


