# Habilita o Hibernate ORM para mapear a persistência
quarkus.hibernate-orm.enabled=true

# Desativa o Dev Services local para evitar que o Quarkus tente subir um banco Docker
quarkus.datasource.devservices.enabled=false

# Configuração do Driver Nativo PostgreSQL para o Supabase
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${SUPABASE_DB_URL}
quarkus.datasource.username=${SUPABASE_DB_USER}
quarkus.datasource.password=${SUPABASE_DB_PASSWORD}

# ALERTA DE ESTRATÉGIA DE SCHEMA:
# 'update' atualiza ou cria as tabelas que faltam no Supabase sem deletar os dados existentes.
# NÃO use 'drop-and-create' aqui, ou você limpará o seu banco cloud toda vez que iniciar o app!
quarkus.hibernate-orm.database.generation=update

# Executa cargas automáticas iniciais se necessário (opcional)
quarkus.hibernate-orm.sql-load-script=import.sql

# Configuração de IA com o Google Gemini
quarkus.langchain4j.ai.gemini.api-key=${GEMINI_API_KEY}