# Desabilita o Hibernate e a conexão com o banco temporariamente
quarkus.hibernate-orm.enabled=true 
quarkus.datasource.devservices.enabled=false

# Variáveis do Supabase (mantidas para uso futuro)
supabase.url=https://adawyyxeoanejdkosotk.supabase.co
supabase.anon.key=sb_publishable_9xhFJVhPX-m3tXpcPl0Kmw_r2X0XBjA