# Desabilita o Hibernate e a conexão com o banco temporariamente
quarkus.hibernate-orm.enabled=false
quarkus.datasource.devservices.enabled=false

# Variáveis do Supabase (mantidas para uso futuro)
supabase.url=${SUPABASE_URL}
supabase.anon.key=${SUPABASE_ANON_KEY}