# --- ETAPA 1: Compilação (O Docker vai fazer o build sozinho) ---
FROM maven:3.9.8-eclipse-temurin-21 AS build
COPY pom.xml /code/
COPY src /code/src
WORKDIR /code
RUN mvn clean package -DskipTests

# --- ETAPA 2: Execução (Imagem leve de produção) ---
FROM registry.access.redhat.com/ubi8/openjdk-21-runtime:1.20
ENV LANGUAGE='en_US:en'
COPY --from=build /code/target/quarkus-app/ /deployments/
EXPOSE 8080
USER 185
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"