create table salas (
    id bigint generated by default as identity primary key,
    nome varchar(120) not null,
    capacidade integer not null,
    localizacao varchar(180),
    status varchar(30) not null,
    constraint ck_salas_capacidade check (capacidade > 0),
    constraint ck_salas_status check (status in ('DISPONIVEL', 'INDISPONIVEL', 'MANUTENCAO'))
);

create table equipamentos (
    id bigint generated by default as identity primary key,
    sala_id bigint not null,
    nome varchar(120) not null,
    descricao varchar(255),
    tipo varchar(80) not null,
    status varchar(30) not null,
    constraint fk_equipamentos_salas foreign key (sala_id) references salas (id),
    constraint ck_equipamentos_status check (status in ('DISPONIVEL', 'INDISPONIVEL', 'MANUTENCAO'))
);

create table reservas (
    id bigint generated by default as identity primary key,
    sala_id bigint not null,
    responsavel varchar(120) not null,
    data_hora_inicio timestamp not null,
    data_hora_fim timestamp not null,
    status varchar(30) not null,
    constraint fk_reservas_salas foreign key (sala_id) references salas (id),
    constraint ck_reservas_periodo check (data_hora_inicio < data_hora_fim),
    constraint ck_reservas_status check (status in ('ATIVA', 'CANCELADA'))
);

create index idx_reservas_sala_periodo on reservas (sala_id, data_hora_inicio, data_hora_fim);
create index idx_reservas_status on reservas (status);
create index idx_equipamentos_sala on equipamentos (sala_id);
