create table usuarios (
    id bigint generated by default as identity primary key,
    nome varchar(120) not null,
    role varchar(30) not null,
    cargo varchar(120),
    constraint ck_usuarios_role check (role in ('FUNCIONARIO', 'GESTOR', 'ADMIN'))
);

create table posicoes (
    id bigint generated by default as identity primary key,
    codigo varchar(80) not null,
    descricao varchar(255),
    localizacao varchar(180),
    recursos varchar(255),
    status varchar(30) not null,
    constraint ck_posicoes_status check (status in ('DISPONIVEL', 'INDISPONIVEL', 'MANUTENCAO'))
);

alter table reservas alter column sala_id drop not null;
alter table reservas add column usuario_id bigint;
alter table reservas add column posicao_id bigint;

alter table reservas
    add constraint fk_reservas_usuarios foreign key (usuario_id) references usuarios (id);

alter table reservas
    add constraint fk_reservas_posicoes foreign key (posicao_id) references posicoes (id);

alter table reservas add constraint ck_reservas_recurso check (
    (sala_id is not null and posicao_id is null)
    or (sala_id is null and posicao_id is not null)
);

create index idx_reservas_posicao_periodo on reservas (posicao_id, data_hora_inicio, data_hora_fim);
create index idx_reservas_usuario on reservas (usuario_id);
create index idx_posicoes_status on posicoes (status);
