# Chave da API do Gemini
ai.api.key=AIzaSyA0vGQSe7nMhWL2hAX7yLtJU3yxwRqOSgw

# URL base do Gemini
quarkus.rest-client."ai-api".url=https://generativelanguage.googleapis.com

supabase.url=https://adawyyxeoanejdkosotk.supabase.co
supabase.key=sb_secret_da5zSew6ZDKJd0TYfsi_dQ_DHB842LV

# Libera o Quarkus para receber requisições do frontend no navegador
quarkus.http.cors=true
quarkus.http.cors.origins=*
# (Nota: O '*' libera qualquer porta no ambiente de desenvolvimento)