create table if not exists usuarios (
    id bigint generated by default as identity primary key,
    nome varchar(120) not null,
    role varchar(30) not null,
    cargo varchar(120),
    constraint ck_usuarios_role check (role in ('FUNCIONARIO', 'GESTOR', 'ADMIN'))
);

create table if not exists posicoes (
    id bigint generated by default as identity primary key,
    codigo varchar(80) not null,
    descricao varchar(255),
    localizacao varchar(180),
    recursos varchar(255),
    status varchar(30) not null,
    constraint ck_posicoes_status check (status in ('DISPONIVEL', 'INDISPONIVEL', 'MANUTENCAO'))
);

alter table if exists reservas alter column sala_id drop not null;
alter table if exists reservas add column if not exists usuario_id bigint;
alter table if exists reservas add column if not exists posicao_id bigint;

do $$
begin
    if to_regclass('public.reservas') is not null
        and to_regclass('public.usuarios') is not null
        and not exists (select 1 from pg_constraint where conname = 'fk_reservas_usuarios')
    then
        alter table reservas
            add constraint fk_reservas_usuarios foreign key (usuario_id) references usuarios (id);
    end if;

    if to_regclass('public.reservas') is not null
        and to_regclass('public.posicoes') is not null
        and not exists (select 1 from pg_constraint where conname = 'fk_reservas_posicoes')
    then
        alter table reservas
            add constraint fk_reservas_posicoes foreign key (posicao_id) references posicoes (id);
    end if;

    if to_regclass('public.reservas') is not null
        and not exists (select 1 from pg_constraint where conname = 'ck_reservas_recurso')
    then
        alter table reservas add constraint ck_reservas_recurso check (
            (sala_id is not null and posicao_id is null)
            or (sala_id is null and posicao_id is not null)
        );
    end if;
end $$;

create index if not exists idx_reservas_posicao_periodo on reservas (posicao_id, data_hora_inicio, data_hora_fim);
create index if not exists idx_reservas_usuario on reservas (usuario_id);
create index if not exists idx_posicoes_status on posicoes (status);
