create table if not exists funcionario (
    id bigint generated by default as identity primary key,
    nome text,
    email text unique,
    cargo text,
    role text,
    posicao_preferencial text,
    created_at timestamptz default now()
);

create table if not exists sala (
    id bigint generated by default as identity primary key,
    nome text not null,
    localizacao text,
    tipo text,
    categoria text,
    descricao text,
    capacidade integer,
    status text,
    disponivel boolean default true,
    planta_url text,
    created_at timestamptz default now()
);

create table if not exists posicao (
    id bigint generated by default as identity primary key,
    sala_id bigint references sala(id) on delete cascade,
    codigo_cadeira text not null,
    descricao text,
    localizacao text,
    recursos text,
    coordenadas_x numeric,
    coordenadas_y numeric,
    status text,
    disponivel boolean default true,
    created_at timestamptz default now()
);

create table if not exists equipamento (
    id bigint generated by default as identity primary key,
    sala_id bigint references sala(id) on delete cascade,
    posicao_id bigint references posicao(id) on delete cascade,
    nome text not null,
    descricao text,
    tipo text not null,
    status text default 'DISPONIVEL',
    created_at timestamptz default now()
);

create table if not exists reserva (
    id bigint generated by default as identity primary key,
    funcionario_id bigint references funcionario(id) on delete cascade,
    sala_id bigint references sala(id) on delete set null,
    posicao_id bigint references posicao(id) on delete set null,
    responsavel text,
    data_inicio timestamp,
    data_fim timestamp,
    status text default 'ATIVA',
    created_at timestamptz default now()
);

create index if not exists idx_reserva_sala_periodo on reserva (sala_id, data_inicio, data_fim);
create index if not exists idx_reserva_posicao_periodo on reserva (posicao_id, data_inicio, data_fim);
create index if not exists idx_reserva_status on reserva (status);
create index if not exists idx_equipamento_sala on equipamento (sala_id);
create index if not exists idx_equipamento_posicao on equipamento (posicao_id);
