create table if not exists funcionario (
    id bigint generated by default as identity primary key,
    nome text,
    email text unique,
    cargo text,
    role text,
    posicao_preferencial text,
    created_at timestamptz default now()
);

create table if not exists sala (
    id bigint generated by default as identity primary key,
    nome text not null,
    localizacao text,
    tipo text,
    categoria text,
    descricao text,
    capacidade integer,
    status text,
    disponivel boolean default true,
    planta_url text,
    created_at timestamptz default now()
);

create table if not exists posicao (
    id bigint generated by default as identity primary key,
    sala_id bigint references sala(id) on delete cascade,
    codigo_cadeira text not null,
    descricao text,
    localizacao text,
    recursos text,
    coordenadas_x numeric,
    coordenadas_y numeric,
    status text,
    disponivel boolean default true,
    created_at timestamptz default now()
);

create table if not exists reserva (
    id bigint generated by default as identity primary key,
    funcionario_id bigint references funcionario(id) on delete cascade,
    sala_id bigint references sala(id) on delete set null,
    posicao_id bigint references posicao(id) on delete set null,
    responsavel text,
    data_inicio timestamp,
    data_fim timestamp,
    status text default 'ATIVA',
    created_at timestamptz default now()
);

create table if not exists equipamento (
    id bigint generated by default as identity primary key,
    sala_id bigint references sala(id) on delete cascade,
    posicao_id bigint references posicao(id) on delete cascade,
    nome text not null,
    descricao text,
    tipo text not null,
    status text default 'DISPONIVEL',
    created_at timestamptz default now()
);

alter table funcionario add column if not exists role text;
alter table funcionario add column if not exists cargo text;
alter table funcionario add column if not exists posicao_preferencial text;
alter table funcionario alter column role type text using role::text;

alter table sala add column if not exists capacidade integer;
alter table sala add column if not exists localizacao text;
alter table sala add column if not exists status text;
alter table sala add column if not exists disponivel boolean default true;
alter table sala add column if not exists tipo text;
alter table sala add column if not exists categoria text;
alter table sala add column if not exists descricao text;
alter table sala add column if not exists planta_url text;

alter table posicao add column if not exists sala_id bigint;
alter table posicao add column if not exists codigo_cadeira text;
alter table posicao add column if not exists descricao text;
alter table posicao add column if not exists localizacao text;
alter table posicao add column if not exists recursos text;
alter table posicao add column if not exists coordenadas_x numeric;
alter table posicao add column if not exists coordenadas_y numeric;
alter table posicao add column if not exists status text;
alter table posicao add column if not exists disponivel boolean default true;

alter table reserva add column if not exists funcionario_id bigint;
alter table reserva add column if not exists sala_id bigint;
alter table reserva add column if not exists posicao_id bigint;
alter table reserva add column if not exists responsavel text;
alter table reserva add column if not exists data_inicio timestamp;
alter table reserva add column if not exists data_fim timestamp;
alter table reserva add column if not exists status text default 'ATIVA';

update funcionario
set role = case
    when upper(coalesce(role::text, cargo, '')) in ('ADMIN', 'ADMINISTRADOR') then 'ADMIN'
    when upper(coalesce(role::text, cargo, '')) in ('GESTOR', 'MANAGER') then 'GESTOR'
    else 'FUNCIONARIO'
end
where role is null or role::text = '' or upper(role::text) not in ('FUNCIONARIO', 'GESTOR', 'ADMIN');

update sala
set capacidade = 1
where capacidade is null or capacidade < 1;

update sala
set status = case
    when status is null or status = '' then case when coalesce(disponivel, true) then 'DISPONIVEL' else 'INDISPONIVEL' end
    when upper(status) in ('DISPONIVEL', 'INDISPONIVEL', 'MANUTENCAO') then upper(status)
    else case when coalesce(disponivel, true) then 'DISPONIVEL' else 'INDISPONIVEL' end
end;

update sala
set disponivel = status = 'DISPONIVEL';

update posicao
set codigo_cadeira = 'P' || id::text
where codigo_cadeira is null or codigo_cadeira = '';

update posicao
set status = case
    when status is null or status = '' then case when coalesce(disponivel, true) then 'DISPONIVEL' else 'INDISPONIVEL' end
    when upper(status) in ('DISPONIVEL', 'INDISPONIVEL', 'MANUTENCAO') then upper(status)
    else case when coalesce(disponivel, true) then 'DISPONIVEL' else 'INDISPONIVEL' end
end;

update posicao
set disponivel = status = 'DISPONIVEL';

update reserva
set status = case
    when lower(coalesce(status, '')) = 'cancelada' then 'CANCELADA'
    else 'ATIVA'
end;

update reserva r
set responsavel = f.nome
from funcionario f
where r.funcionario_id = f.id
  and (r.responsavel is null or r.responsavel = '');

update reserva
set responsavel = 'Responsavel nao informado'
where responsavel is null or responsavel = '';

update reserva
set data_inicio = coalesce(data_inicio, created_at, now())
where data_inicio is null;

update reserva
set data_fim = data_inicio + interval '8 hours'
where data_fim is null;

update reserva r
set sala_id = p.sala_id
from posicao p
where r.posicao_id = p.id
  and r.sala_id is null
  and p.sala_id is not null;

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'fk_posicao_sala') then
        alter table posicao
            add constraint fk_posicao_sala foreign key (sala_id) references sala(id) on delete cascade;
    end if;

    if not exists (select 1 from pg_constraint where conname = 'fk_reserva_funcionario') then
        alter table reserva
            add constraint fk_reserva_funcionario foreign key (funcionario_id) references funcionario(id) on delete cascade;
    end if;

    if not exists (select 1 from pg_constraint where conname = 'fk_reserva_sala') then
        alter table reserva
            add constraint fk_reserva_sala foreign key (sala_id) references sala(id) on delete set null;
    end if;

    if not exists (select 1 from pg_constraint where conname = 'fk_reserva_posicao') then
        alter table reserva
            add constraint fk_reserva_posicao foreign key (posicao_id) references posicao(id) on delete set null;
    end if;
end $$;

create index if not exists idx_sala_status on sala (status);
create index if not exists idx_posicao_sala_id on posicao (sala_id);
create index if not exists idx_posicao_status on posicao (status);
create index if not exists idx_reserva_funcionario_id on reserva (funcionario_id);
create index if not exists idx_reserva_sala_periodo on reserva (sala_id, data_inicio, data_fim);
create index if not exists idx_reserva_posicao_periodo on reserva (posicao_id, data_inicio, data_fim);
create index if not exists idx_reserva_status on reserva (status);
create index if not exists idx_equipamento_sala on equipamento (sala_id);
create index if not exists idx_equipamento_posicao on equipamento (posicao_id);
