create table funcionario (
    id bigint generated by default as identity primary key,
    nome varchar(120),
    email varchar(180),
    cargo varchar(120),
    role varchar(30),
    posicao_preferencial varchar(120),
    created_at timestamp default current_timestamp
);

create table sala (
    id bigint generated by default as identity primary key,
    nome varchar(120) not null,
    localizacao varchar(180),
    tipo varchar(80),
    categoria varchar(80),
    descricao varchar(255),
    capacidade integer,
    status varchar(30),
    disponivel boolean default true,
    planta_url varchar(255),
    created_at timestamp default current_timestamp
);

create table posicao (
    id bigint generated by default as identity primary key,
    sala_id bigint,
    codigo_cadeira varchar(80) not null,
    descricao varchar(255),
    localizacao varchar(180),
    recursos varchar(255),
    coordenadas_x numeric,
    coordenadas_y numeric,
    status varchar(30),
    disponivel boolean default true,
    created_at timestamp default current_timestamp,
    constraint fk_posicao_sala foreign key (sala_id) references sala (id)
);

create table equipamento (
    id bigint generated by default as identity primary key,
    sala_id bigint,
    posicao_id bigint,
    nome varchar(120) not null,
    descricao varchar(255),
    tipo varchar(80) not null,
    status varchar(30),
    created_at timestamp default current_timestamp,
    constraint fk_equipamento_sala foreign key (sala_id) references sala (id),
    constraint fk_equipamento_posicao foreign key (posicao_id) references posicao (id)
);

create table reserva (
    id bigint generated by default as identity primary key,
    funcionario_id bigint,
    sala_id bigint,
    posicao_id bigint,
    responsavel varchar(120),
    data_inicio timestamp,
    data_fim timestamp,
    status varchar(30),
    created_at timestamp default current_timestamp,
    constraint fk_reserva_funcionario foreign key (funcionario_id) references funcionario (id),
    constraint fk_reserva_sala foreign key (sala_id) references sala (id),
    constraint fk_reserva_posicao foreign key (posicao_id) references posicao (id)
);

create index idx_reserva_sala_periodo on reserva (sala_id, data_inicio, data_fim);
create index idx_reserva_posicao_periodo on reserva (posicao_id, data_inicio, data_fim);
create index idx_reserva_status on reserva (status);
create index idx_equipamento_sala on equipamento (sala_id);
create index idx_equipamento_posicao on equipamento (posicao_id);
